// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BillingProvider.Core.Models;
//
//    var getDataKktRequest = GetDataKktRequest.FromJson(jsonString);

namespace BillingProvider.Core.Models
{
    using Newtonsoft.Json;

    public partial class GetDataKktRequest
    {
        [JsonProperty("Command", Required = Required.Always)]
        public string Command { get; set; }

        [JsonProperty("NumDevice", Required = Required.Always)]
        public long NumDevice { get; set; }

        [JsonProperty("IdCommand", Required = Required.Always)]
        public string IdCommand { get; set; }
    }

    public partial class GetDataKktRequest
    {
        public static GetDataKktRequest FromJson(string json) => JsonConvert.DeserializeObject<GetDataKktRequest>(json, Converter.Settings);
    }
}