name: .NET Desktop

on:
  push:
    branches: [ master ]
    tags: 0.**
  pull_request:
    branches: [ master ]
    tags: 0.**

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - run: nuget restore BillingProvider.sln

    - name: MSBuild
      working-directory: BillingProvider.WinForms
      run: msbuild BillingProvider.WinForms.csproj
      
    - name: GitHub Environment Variables Action
      uses: FranzDiebold/github-env-vars-action@v1.2.0
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: BillingProvider.$Env:GITHUB_REF_NAME.0.zip
      
