name: Build and deploy

on:
  push:
    tags: v0.*

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
    
    - name: Get version
      id: get_ver
      run:
        $SOURCE_TAG = ${env:GITHUB_REF} -replace ‘refs/tags/v’, ‘’
        
        echo “::set-env name=SOURCE_TAG::$SOURCE_TAG”

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - run: nuget restore BillingProvider.sln

    - name: MSBuild
      working-directory: BillingProvider.WinForms
      run: 
        msbuild BillingProvider.WinForms.csproj -property:Configuration=Release /p:VersionAssembly=${{ env.SOURCE_TAG }}.0
        
        cd ..
         
        dir  
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v${{ env.SOURCE_TAG }}
        release_name: Release v${{ env.SOURCE_TAG }}
        body: |
          Automated Release by GitHub Action CI
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../BillingProvider.1.0.0.0.zip
        asset_name: BillingProvider.1.0.0.0.zip
        body_path: ../ReleaseNotes.md
        asset_content_type: zip      
