name: test tag

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - name: set variable
      id: get_ver
      run: 
        echo ::set-env name=VERSION::${env:GITHUB_REF} -replace ‘refs/tags/’, ‘’
      
    - name: get variable
      run: echo ${{ env.VERSION }}
