name: test tag

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - name: set variable
      id: get_ver
      run:
        $SOURCE_TAG = ${env:GITHUB_REF} -replace ‘refs/tags/’, ‘’
        echo "::set-output name=VERSION::$SOURCE_TAG"
      
    - name: get variable
      run: echo "::${{ steps.get_ver.outputs.VERSION }}"
