name: test tag

on:
  push:
    branches: [ master ]
    tags: v*

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - name: test variable
      run: echo ${{ github.event.release.tag_name }}
